# This is a configuration file for instr_main.py

--- # document start

## Addresses of each devices  #####################


## list ###########################################

## dictionary #####################################

... # document end