# This is a configuration file for setting up passive sweeps such as insertion loss
# This will be loaded to sweeps_main.py when it starts running

--- # document start
### General variables for testing #################
gpib_num: 0
addr: 20 # instrument address
folder: "Chip_5" # under results folder
structure: "Si_wg" # the name of the file {structure}_DCSweeps_data


## var  ###########################################
power: 10       # output power [dBm]
w_start: 1535  # start wavelength [nm]
w_stop: 1575    # end wavelength [nm]
step: 5        # sweep step [pm]


## list ###########################################
lengths:
  - 24
  - 16
  - 4
  - 0
  - 20
  - 8
  - 12


## dictionary #####################################

... # document end