# This is a configuration file for setting up python graphs
# This will be loaded to plot.py when it starts running
--- # document start

## var  ###########################################
structure: "KTN" # e.g. {structure}_iloss_data.py
func: "plt_len_loss_excel" # Inspect PlotGraphs for available functions
unit: "mm" # unit 

## list ###########################################
folders: # select folder name under results
  - "Chip_3"

sheets: # only for excel
  - "IL W=0.5 angle=18"


## Length Loss Plots Only Variables #####################################
exp_lambda: 1550 # wavelength of interest [nm]
lambda_avgrange: 10 # wavelength range for averaging data points [nm] e.g. 10: x-5 to x+5
columns_dropping:
  Chip_3:
    - " 5.5"
  Chip_4:
    -
  Chip_5:
    -

## Wavelength Loss Plots Only Variables ################################
columns_plot: 
  Chip_3:
    - " 1.5"
    - " 2.5" 
    - " 3.5"
    - " 4.5"
    - " 6.5"

  Chip_4:
  Chip_5:

... # document end