# This is a configuration file for setting up python graphs
# This will be loaded to plot.py when it starts running
--- # document start

## General Variables  ###########################################
fname: "KTN_chip3_ktn_trans" # <fname>.csv or <fname>.xlsx
func: "plt_lambda_loss_excel" # Inspect PlotGraphs for available functions
no_channels: 1 # number of channels

title: "KTN Chip Transition"
end_of_legend: "" # legend = {folder_name}_{length}{end_of_legend}
unit: "mm" # unit (being on the y-axis)

folders: # select folder name under results
  - "Chip_3"

sheets: # only for excel
  - "1.5um"


## Length Loss Plots Only Variables #####################################
exp_lambda: 1550 # wavelength of interest [nm]
lambda_avgrange: 5 # wavelength range for averaging data points [nm] e.g. 10: x-5 to x+5
columns_drop:
  Chip_3:
  Chip_4:
  Chip_5:

## Wavelength Loss Plots Only Variables ################################
columns_plot: 
  Chip_3:
    - "0"
    - "2" 
    - "4"
    - "6"
    - "8"
    - "10"

  Chip_4:
  Chip_5:

... # document end