# This is a configuration file for setting up python graphs
# This will be loaded to plot.py when it starts running
--- # document start

## var  ###########################################
structure: "KTN" # e.g. {structure}_iloss_data.py


## list ###########################################
folders: # select folder name under results
  - "Chip_3"

sheets: # only for excel
  - "IL W=0.5 angle=18"


## dictionary #####################################
columns_dropping: # only used for length loss plots
  Chip_3:
    - " 5.5"
  Chip_4:
    -
  Chip_5:
    -

columns_plot: # only used for wavelength loss plots
  Chip_3:
    - " 1.5"
    - " 2.5" 
    - " 3.5"
    - " 4.5"
    - " 6.5"

  Chip_4:
  Chip_5:

... # document end