# This is a configuration file for setting up python graphs
# This will be loaded to plot.py when it starts running
--- # document start

#####################################################
# key - value
# e.g. a: "hello", b: 35
structure: "KTN" # e.g. {structure}_iloss_data.py


#####################################################
# list
# e.g.
# var:
#   - "name"
#   - "weight"
folders: # select folder name under results
  - "Chip_3"

sheets: # only for excel
  - "IL W=1"


#####################################################
# map
# e.g.
# var:
#   "name": "melody"
#   "weight": 20
columns_dropping: # only used for length loss plots
  Chip_3:
    - " 5.5"
  Chip_4:
    -
  Chip_5:
    -

columns_plot: # only used for wavelength loss plots
  Chip_3:
    - " 4.5"
  Chip_4:
    - 0.0
  Chip_5:
    - 0.0

... # document end