## Addresses of each devices  #############################
# NOTE: You only have to set the correct address for      #
# instruments related to your operations                  #
#                                                         #
# e.g. Each of the x should be replaced                   #
#   GPIB Device = GPIBx::x::INSTR                         #
#   COM  Device = COMx                                    #     
###########################################################                                                      
instr_addrs:                                             
    "Agilent816xB_Addr": "GPIB0::20::INSTR"            
    "KeysightE8257D_Addr": ""
    "KeysightFlexDCA_Addr": ""
    "Keysight86100D_Addr": ""
    "FiberlabsAMP_Addr": "GPIB0:1:INSTR"
###########################################################

# agilent8163B ######################################
agilent816xB:
  model: "8164" # "8163" or "8164" type
  wavelength: 1550 # [nm]
  power: 10 # [dBm]
  period: 200.0E-03 # [s]
  reset: false
  op: # find operating wavelength configuration
    db: -3
    target: 1535 # [nm]
    xrange: 10 # [nm]
    step: 5 # [pm]
    speed: 5 # [nm/s]
#####################################################

# high_speed ########################################
high_speed:
  frequency: 1 # [GHz]
  odratio: "unit" # Set the output clock divide ratio
#####################################################

# fiberlabsAMP ######################################
fiberlabsAMP:
  # Prediction-only variables #########
  prediction: False # If true, makes prediction based on the wavelength [nm] and the loss [dB].
  model_file: "" # Required when "prediction" is true
  wavelength: 1550 # [nm]
  loss: 10 # [dBm]
  #####################################
  mode: "ACC" # ACC - current, ALC - power
  channel: 1
  current: 10 # [mA]
  power: 10 # [dBm]
#####################################################
  