# This is a configuration file for setting up passive sweeps such as insertion loss
# This will be loaded to sweeps_main.py when it starts running

--- # document start
### General variables for testing #################
folder: "Chip_5" # under results folder
fname: "Si_wg" # in csv
func:

instr_addrs:
  mm: "GPIB0::25::INSTR" 

## var  ###########################################
power: 10       # output power [dBm]
w_start: 1535  # start wavelength [nm]
w_stop: 1575    # end wavelength [nm]
w_step: 5        # sweep step [pm]


## list ###########################################
lengths:
  - 24
  - 16
  - 4
  - 0
  - 20
  - 8
  - 12


## dictionary #####################################

... # document end