# This is a configuration file for setting up python graphs
# This will be loaded to plot.py when it starts running
--- # document start

## General Variables  ###########################################

func: "plt_len_loss_excel" # Inspect PlotGraphs for available functions
no_channels: 1 # number of channels
normalise: true

files: 
  "./results/Chip_6/result.xlsx": # path/to/file
    - "KTN One Straight (20.5)" # sheetname
    

## Plot Variables ###############################################
title: ""
xlabel: "Length [mm]"
ylabel: "Normalised Loss [dB]"
end_of_legend: "" # legend = {length}{end_of_legend}



# Filtering signal parameters - moving average ##################
signal_filter: false # require filtering the signal?
window_size: 100


## Length Loss Plots Only Variables #####################################
exp_lambda: 1550 # wavelength of interest [nm]
lambda_avgrange: 3 # wavelength range for averaging data points [nm] e.g. 10: x-5 to x+5
columns_drop:
  "./results/Chip_6/result.xlsx":
    "KTN One Straight (20.5)":
      - 1.5
      - 6.5
  "./results/Chip_8/result.xlsx":
    "KTN 4 Straights":
      - 6
      - 12


## Wavelength Loss Plots Only Variables #################################
# if nothing is specified then it will plot all data ####################
columns_plot: 


## DC Loss Plots Only Variables #################################
dc_drop:

... # document end