# This is a configuration file for setting up python graphs
# This will be loaded to plot.py when it starts running
--- # document start

## General Variables  ###########################################

fname: "Chip_8.xlsx" # <fname>.csv or <fname>.xlsx
func: "plt_lambda_loss_excel" # Inspect PlotGraphs for available functions
no_channels: 1 # number of channels

folders: # select folder name under results
  - "./results/Chip_8"

sheets: # excel only
  - "KTN 4 Straights 2"


## Plot Variables ###############################################
title: "KTN 4 Straights 2"
xlabel: "Wavelength [nm]"
ylabel: "Loss [dB/mm]"
end_of_legend: "" # legend = {folder_name}_{length}{end_of_legend}


# Filtering signal parameters - moving average ##################
signal_filter: false # require filtering the signal?
window_size: 100


## Length Loss Plots Only Variables #####################################
exp_lambda: 1550 # wavelength of interest [nm]
lambda_avgrange: 1 # wavelength range for averaging data points [nm] e.g. 10: x-5 to x+5
columns_drop:
  Chip_8:
    - 6
    - 8
    - 12


## Wavelength Loss Plots Only Variables #################################
# if nothing is specified then it will plot all data ####################
columns_plot: 
  Chip_9:
  Chip_6:
  Chip_4:
  Chip_5:


## DC Loss Plots Only Variables #################################
dc_drop:

... # document end