name: Python package

on: [push]

jobs:
  build:
    
    runs-on: windows-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Python 3.6
        uses: actions/setup-python@v4
        with:
          python-version: '3.6'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test with pytest
        run: |
          python -m pip install -U pytest
          pytest --ignore=configs --ignore=pyoctal --ignore=results --ignore=tools

